config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    delete :remove_image
  end

  post 'login', to: 'posts#login'
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post

  attr_accessible :image_url, :post_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :images

  attr_accessible :title, :description, :post_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = case params[:post_type]
      when 'usefully'
        Post.where(post_type: 'usefully')
      when 'fine'
        Post.where(post_type: 'fine')
      else
        Post.where(post_type: 'rule')
    end

    @posts = @posts.order(:title)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(params[:post])

    if params[:images]
      params[:images].each do |image|
        @post.images.create(image_url: image) unless image.blank?
      end
    end

    if @post.valid?
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])

    if params[:images]
      params[:images].each do |image|
        @post.images.create(image_url: image) unless image.blank?
      end
    end

    if @post.valid?
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def login
    cookies[:logged] = true if params[:sign][:login] == 'krotten' && params[:sign][:password] == 'khazmodan'
  end

  def remove_image
    @post = Post.find(params[:post_id])
    @post.images.find(params[:image_id]).destroy

    @post.images.reload
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_login_partial.html.haml
= form_for :sign, url: login_path, remote: true do |f|

  = f.label :login, 'Логин', class: 'white-label'
  = f.text_field :login, autocomplete: "off"

  = f.label :password, 'Пароль', class: 'white-label'
  = f.password_field :password

  = f.submit 'Залогинится', name: nil, class: 'button'

:javascript
  $('input:submit').click(function(e) {
    $('#login-form').hide();
  });

app/views/layouts/_menu.html.haml
%ul
  %li
    = link_to 'Правила', posts_path(post_type: 'rule'), class: "#{ (!params[:post_type].present? || params[:post_type] == 'rule') ? 'chosen' : ''}"
  %li
    = link_to 'Информация', posts_path(post_type: 'usefully'), class: "#{ params[:post_type] == 'usefully' ? 'chosen' : ''}"
  %li
    = link_to 'Штрафы', posts_path(post_type: 'fine'), class: "#{ params[:post_type] == 'fine' ? 'chosen' : ''}"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title
    Bezlikie
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  .small-12.page-head
    %h1
      Альянс "
      = link_to 'Без', '', id: 'login'
      ликие"

      - if cookies[:logged]
        = link_to '+', new_post_path, class: 'add-post'

    #login-form
      .row
        .small-6.columns.container
          = render 'layouts/login_partial'

  %section.admin
    .small-12#main
      .row
        = yield

:javascript
  $('#login-form').hide();

  $('#login').click(function(e) {
    e.preventDefault();
    e.stopPropagation();

    $('#login-form').show();
  });

app/views/posts/_images.html.haml
- if @post.images.present?
  .row
    - @post.images.each do |image|
      .image-min-container
        .image-wrapper
          = image_tag image.image_url, class: 'post-image-min'
        = link_to 'Удалить изображение', post_remove_image_path(post_id: @post.id, image_id: image.id), data: { remote: true, confirm: 'Вы уверены?', method: :delete }, class: 'button warning'

app/views/posts/edit.html.haml
.small-10.columns.container
  .row
    %h3
      Редактировать сообщение

  .row
    = form_for @post do |f|
      .row
        = f.label :title, 'Заголовок'
        = f.text_field :title, maxlength: 60

      .row
        = f.label :post_type, 'Тип сообщения'

        = f.radio_button :post_type, 'rule', checked: "#{@post.post_type == 'rule' ? 'checked' : ''}"
        = f.label :post_type, 'Правила'

        = f.radio_button :post_type, 'usefully', checked: "#{@post.post_type == 'usefully' ? 'checked' : ''}"
        = f.label :post_type, 'Полезная информация'

        = f.radio_button :post_type, 'fine', checked: "#{@post.post_type == 'fine' ? 'checked' : ''}"
        = f.label :post_type, 'Штрафы'

      .row
        = f.label :description, 'Текст сообщения'
        = f.text_area :description, rows: 12, class: 'tinymce'
        = tinymce

      #images_container
        = render 'images'

      .row#images
        = link_to 'Добавить URL картинки', '', class: 'button success add-image'

      .post-buttons
        = f.submit 'Обновить сообщение', name: nil, class: 'button'
        = link_to 'Назад', posts_path, class: 'button alert'

:javascript
  $('.add-image').click(function(e) {
    e.preventDefault();

    $('#images').append('<label for="images">URL изображения</label><input type="text" name="images[]">');
  });

app/views/posts/index.html.haml
.small-4.columns.container.left#menu
  = render 'layouts/menu'

.small-8.columns.container
  - @posts.each do |p|
    .row
      .small-12.columns.left
        %h3
          = link_to p.title, post_path(p)

    %hr

app/views/posts/login.js.haml
:plain
  location.reload();

app/views/posts/new.html.haml
.small-10.columns.container
  .row
    %h3
      Новое сообщение

  .row
    = form_for @post do |f|
      .row
        = f.label :title, 'Заголовок'
        = f.text_field :title, maxlength: 60

      .row
        = f.label :post_type, 'Тип сообщения'

        = f.radio_button :post_type, 'rule', checked: 'checked'
        = f.label :post_type, 'Правила'

        = f.radio_button :post_type, 'usefully'
        = f.label :post_type, 'Полезная информация'

        = f.radio_button :post_type, 'fine'
        = f.label :post_type, 'Штрафы'

      .row
        = f.label :description, 'Текст сообщения'
        = f.text_area :description, rows: 12, class: 'tinymce'
        = tinymce

      .row#images
        = link_to 'Добавить URL картинки', '', class: 'button success add-image'

      .post-buttons
        = f.submit 'Создать сообщение', name: nil, class: 'button'
        = link_to 'Назад', posts_path, class: 'button alert'

:javascript
  $('.add-image').click(function(e) {
    e.preventDefault();

    $('#images').append('<label for="images">URL изображения</label><input type="text" name="images[]">');
  });

app/views/posts/remove_image.js.haml
:plain
  $('#images_container').html("#{j(render partial: 'images')}");

app/views/posts/show.html.haml
.small-8.columns.container
  - if cookies[:logged]
    = link_to 'Редактировать', edit_post_path(@post), class: 'button'
    = link_to 'Удалить', post_path(@post), data: { confirm: 'Вы уверены?', method: :delete }, class: 'button'

  .row
    %h1
      = @post.title

  %hr

  .row
    .small-12
      = @post.description.html_safe

  %hr

  - if @post.images.present?
    .row
      - @post.images.each do |image|
        .small-12
          = image_tag image.image_url, class: 'post-image'

    %hr

  = link_to 'Назад', posts_path(post_type: @post.post_type), class: 'button alert'